#include "translator.h"

QMap<Translator::Language, QString> const Translator::genericLang2Code = {
    {Auto, QStringLiteral("auto")},
    {Afrikaans, QStringLiteral("af")},
    {Albanian, QStringLiteral("sq")},
    {Amharic, QStringLiteral("am")},
    {Arabic, QStringLiteral("ar")},
    {Armenian, QStringLiteral("hy")},
    {Azerbaijani, QStringLiteral("az")},
    {Bashkir, QStringLiteral("ba")},
    {Basque, QStringLiteral("eu")},
    {Belarusian, QStringLiteral("be")},
    {Bengali, QStringLiteral("bn")},
    {Bosnian, QStringLiteral("bs")},
    {Bulgarian, QStringLiteral("bg")},
    {Cantonese, QStringLiteral("yue")},
    {Catalan, QStringLiteral("ca")},
    {Cebuano, QStringLiteral("ceb")},
    {Chichewa, QStringLiteral("ny")},
    {Corsican, QStringLiteral("co")},
    {Croatian, QStringLiteral("hr")},
    {Czech, QStringLiteral("cs")},
    {Danish, QStringLiteral("da")},
    {Dutch, QStringLiteral("nl")},
    {English, QStringLiteral("en")},
    {Esperanto, QStringLiteral("eo")},
    {Estonian, QStringLiteral("et")},
    {Fijian, QStringLiteral("fj")},
    {Filipino, QStringLiteral("fil")},
    {Finnish, QStringLiteral("fi")},
    {French, QStringLiteral("fr")},
    {Frisian, QStringLiteral("fy")},
    {Galician, QStringLiteral("gl")},
    {Georgian, QStringLiteral("ka")},
    {German, QStringLiteral("de")},
    {Greek, QStringLiteral("el")},
    {Gujarati, QStringLiteral("gu")},
    {HaitianCreole, QStringLiteral("ht")},
    {Hausa, QStringLiteral("ha")},
    {Hawaiian, QStringLiteral("haw")},
    {Hebrew, QStringLiteral("he")},
    {HillMari, QStringLiteral("mrj")},
    {Hindi, QStringLiteral("hi")},
    {Hmong, QStringLiteral("hmn")},
    {Hungarian, QStringLiteral("hu")},
    {Icelandic, QStringLiteral("is")},
    {Igbo, QStringLiteral("ig")},
    {Indonesian, QStringLiteral("id")},
    {Irish, QStringLiteral("ga")},
    {Italian, QStringLiteral("it")},
    {Japanese, QStringLiteral("ja")},
    {Javanese, QStringLiteral("jw")},
    {Kannada, QStringLiteral("kn")},
    {Kazakh, QStringLiteral("kk")},
    {Khmer, QStringLiteral("km")},
    {Kinyarwanda, QStringLiteral("rw")},
    {Klingon, QStringLiteral("tlh")},
    {KlingonPlqaD, QStringLiteral("tlh-Qaak")},
    {Korean, QStringLiteral("ko")},
    {Kurdish, QStringLiteral("ku")},
    {Kyrgyz, QStringLiteral("ky")},
    {Lao, QStringLiteral("lo")},
    {Latin, QStringLiteral("la")},
    {Latvian, QStringLiteral("lv")},
    {LevantineArabic, QStringLiteral("apc")},
    {Lithuanian, QStringLiteral("lt")},
    {Luxembourgish, QStringLiteral("lb")},
    {Macedonian, QStringLiteral("mk")},
    {Malagasy, QStringLiteral("mg")},
    {Malay, QStringLiteral("ms")},
    {Malayalam, QStringLiteral("ml")},
    {Maltese, QStringLiteral("mt")},
    {Maori, QStringLiteral("mi")},
    {Marathi, QStringLiteral("mr")},
    {Mari, QStringLiteral("mhr")},
    {Mongolian, QStringLiteral("mn")},
    {Myanmar, QStringLiteral("my")},
    {Nepali, QStringLiteral("ne")},
    {Norwegian, QStringLiteral("no")},
    {Oriya, QStringLiteral("or")},
    {Papiamento, QStringLiteral("pap")},
    {Pashto, QStringLiteral("ps")},
    {Persian, QStringLiteral("fa")},
    {Polish, QStringLiteral("pl")},
    {Portuguese, QStringLiteral("pt")},
    {Punjabi, QStringLiteral("pa")},
    {QueretaroOtomi, QStringLiteral("otq")},
    {Romanian, QStringLiteral("ro")},
    {Russian, QStringLiteral("ru")},
    {Samoan, QStringLiteral("sm")},
    {ScotsGaelic, QStringLiteral("gd")},
    {SerbianCyrillic, QStringLiteral("sr")},
    {SerbianLatin, QStringLiteral("sr-Latin")},
    {Sesotho, QStringLiteral("st")},
    {Shona, QStringLiteral("sn")},
    {SimplifiedChinese, QStringLiteral("zh-CN")},
    {Sindhi, QStringLiteral("sd")},
    {Sinhala, QStringLiteral("si")},
    {Slovak, QStringLiteral("sk")},
    {Slovenian, QStringLiteral("sl")},
    {Somali, QStringLiteral("so")},
    {Spanish, QStringLiteral("es")},
    {Sundanese, QStringLiteral("su")},
    {Swahili, QStringLiteral("sw")},
    {Swedish, QStringLiteral("sv")},
    {Tagalog, QStringLiteral("tl")},
    {Tahitian, QStringLiteral("ty")},
    {Tajik, QStringLiteral("tg")},
    {Tamil, QStringLiteral("ta")},
    {Tatar, QStringLiteral("tt")},
    {Telugu, QStringLiteral("te")},
    {Thai, QStringLiteral("th")},
    {Tongan, QStringLiteral("to")},
    {TraditionalChinese, QStringLiteral("zh-TW")},
    {Turkish, QStringLiteral("tr")},
    {Turkmen, QStringLiteral("tk")},
    {Udmurt, QStringLiteral("udm")},
    {Uighur, QStringLiteral("ug")},
    {Ukrainian, QStringLiteral("uk")},
    {Urdu, QStringLiteral("ur")},
    {Uzbek, QStringLiteral("uz")},
    {Vietnamese, QStringLiteral("vi")},
    {Welsh, QStringLiteral("cy")},
    {Xhosa, QStringLiteral("xh")},
    {Yiddish, QStringLiteral("yi")},
    {Yoruba, QStringLiteral("yo")},
    {YucatecMaya, QStringLiteral("yua")},
    {Zulu, QStringLiteral("zu")}};

QString Translator::getLanguageName(Translator::Language lang) {
  switch (lang) {
    case Auto:
      return tr("Automatically detect");
    case Afrikaans:
      return tr("Afrikaans");
    case Albanian:
      return tr("Albanian");
    case Amharic:
      return tr("Amharic");
    case Arabic:
      return tr("Arabic");
    case Armenian:
      return tr("Armenian");
    case Azerbaijani:
      return tr("Azeerbaijani");
    case Basque:
      return tr("Basque");
    case Bashkir:
      return tr("Bashkir");
    case Belarusian:
      return tr("Belarusian");
    case Bengali:
      return tr("Bengali");
    case Bosnian:
      return tr("Bosnian");
    case Bulgarian:
      return tr("Bulgarian");
    case Catalan:
      return tr("Catalan");
    case Cantonese:
      return tr("Cantonese");
    case Cebuano:
      return tr("Cebuano");
    case SimplifiedChinese:
      return tr("Chinese (Simplified)");
    case TraditionalChinese:
      return tr("Chinese (Traditional)");
    case Corsican:
      return tr("Corsican");
    case Croatian:
      return tr("Croatian");
    case Czech:
      return tr("Czech");
    case Danish:
      return tr("Danish");
    case Dutch:
      return tr("Dutch");
    case English:
      return tr("English");
    case Esperanto:
      return tr("Esperanto");
    case Estonian:
      return tr("Estonian");
    case Fijian:
      return tr("Fijian");
    case Filipino:
      return tr("Filipino");
    case Finnish:
      return tr("Finnish");
    case French:
      return tr("French");
    case Frisian:
      return tr("Frisian");
    case Galician:
      return tr("Galician");
    case Georgian:
      return tr("Georgian");
    case German:
      return tr("German");
    case Greek:
      return tr("Greek");
    case Gujarati:
      return tr("Gujarati");
    case HaitianCreole:
      return tr("Haitian Creole");
    case Hausa:
      return tr("Hausa");
    case Hawaiian:
      return tr("Hawaiian");
    case Hebrew:
      return tr("Hebrew");
    case HillMari:
      return tr("Hill Mari");
    case Hindi:
      return tr("Hindi");
    case Hmong:
      return tr("Hmong");
    case Hungarian:
      return tr("Hungarian");
    case Icelandic:
      return tr("Icelandic");
    case Igbo:
      return tr("Igbo");
    case Indonesian:
      return tr("Indonesian");
    case Irish:
      return tr("Irish");
    case Italian:
      return tr("Italian");
    case Japanese:
      return tr("Japanese");
    case Javanese:
      return tr("Javanese");
    case Kannada:
      return tr("Kannada");
    case Kazakh:
      return tr("Kazakh");
    case Khmer:
      return tr("Khmer");
    case Kinyarwanda:
      return tr("Kinyarwanda");
    case Klingon:
      return tr("Klingon");
    case KlingonPlqaD:
      return tr("Klingon (PlqaD)");
    case Korean:
      return tr("Korean");
    case Kurdish:
      return tr("Kurdish");
    case Kyrgyz:
      return tr("Kyrgyz");
    case Lao:
      return tr("Lao");
    case Latin:
      return tr("Latin");
    case Latvian:
      return tr("Latvian");
    case LevantineArabic:
      return tr("Levantine Arabic");
    case Lithuanian:
      return tr("Lithuanian");
    case Luxembourgish:
      return tr("Luxembourgish");
    case Macedonian:
      return tr("Macedonian");
    case Malagasy:
      return tr("Malagasy");
    case Malay:
      return tr("Malay");
    case Malayalam:
      return tr("Malayalam");
    case Maltese:
      return tr("Maltese");
    case Maori:
      return tr("Maori");
    case Marathi:
      return tr("Marathi");
    case Mari:
      return tr("Mari");
    case Mongolian:
      return tr("Mongolian");
    case Myanmar:
      return tr("Myanmar");
    case Nepali:
      return tr("Nepali");
    case Norwegian:
      return tr("Norwegian");
    case Oriya:
      return tr("Oriya");
    case Chichewa:
      return tr("Chichewa");
    case Papiamento:
      return tr("Papiamento");
    case Pashto:
      return tr("Pashto");
    case Persian:
      return tr("Persian");
    case Polish:
      return tr("Polish");
    case Portuguese:
      return tr("Portuguese");
    case Punjabi:
      return tr("Punjabi");
    case QueretaroOtomi:
      return tr("Queretaro Otomi");
    case Romanian:
      return tr("Romanian");
    case Russian:
      return tr("Russian");
    case Samoan:
      return tr("Samoan");
    case ScotsGaelic:
      return tr("Scots Gaelic");
    case SerbianCyrillic:
      return tr("Serbian (Cyrillic)");
    case SerbianLatin:
      return tr("Serbian (Latin)");
    case Sesotho:
      return tr("Sesotho");
    case Shona:
      return tr("Shona");
    case Sindhi:
      return tr("Sindhi");
    case Sinhala:
      return tr("Sinhala");
    case Slovak:
      return tr("Slovak");
    case Slovenian:
      return tr("Slovenian");
    case Somali:
      return tr("Somali");
    case Spanish:
      return tr("Spanish");
    case Sundanese:
      return tr("Sundanese");
    case Swahili:
      return tr("Swahili");
    case Swedish:
      return tr("Swedish");
    case Tagalog:
      return tr("Tagalog");
    case Tahitian:
      return tr("Tahitian");
    case Tajik:
      return tr("Tajik");
    case Tamil:
      return tr("Tamil");
    case Tatar:
      return tr("Tatar");
    case Telugu:
      return tr("Telugu");
    case Thai:
      return tr("Thai");
    case Tongan:
      return tr("Tongan");
    case Turkish:
      return tr("Turkish");
    case Turkmen:
      return tr("Turkmen");
    case Udmurt:
      return tr("Udmurt");
    case Uighur:
      return tr("Uighur");
    case Ukrainian:
      return tr("Ukrainian");
    case Urdu:
      return tr("Urdu");
    case Uzbek:
      return tr("Uzbek");
    case Vietnamese:
      return tr("Vietnamese");
    case Welsh:
      return tr("Welsh");
    case Xhosa:
      return tr("Xhosa");
    case Yiddish:
      return tr("Yiddish");
    case Yoruba:
      return tr("Yoruba");
    case YucatecMaya:
      return tr("Yucatec Maya");
    case Zulu:
      return tr("Zulu");
    default:
      return QString();
  }
}

Translator::Language Translator::getLanguage(QLocale const &locale) {
  switch (locale.language()) {
    case QLocale::Afrikaans:
      return Afrikaans;
    case QLocale::Albanian:
      return Albanian;
    case QLocale::Amharic:
      return Amharic;
    case QLocale::Arabic:
      return Arabic;
    case QLocale::Armenian:
      return Armenian;
    case QLocale::Azerbaijani:
      return Azerbaijani;
    case QLocale::Basque:
      return Basque;
    case QLocale::Belarusian:
      return Belarusian;
    case QLocale::Bengali:
      return Bengali;
    case QLocale::Bosnian:
      return Bosnian;
    case QLocale::Bulgarian:
      return Bulgarian;
    case QLocale::Catalan:
      return Catalan;
    case QLocale::Chinese:
      return SimplifiedChinese;
    case QLocale::LiteraryChinese:
      return TraditionalChinese;
    case QLocale::Corsican:
      return Corsican;
    case QLocale::Croatian:
      return Croatian;
    case QLocale::Czech:
      return Czech;
    case QLocale::Danish:
      return Danish;
    case QLocale::Dutch:
      return Dutch;
    case QLocale::Esperanto:
      return Esperanto;
    case QLocale::Estonian:
      return Estonian;
    case QLocale::Finnish:
      return Finnish;
    case QLocale::French:
      return French;
    case QLocale::Frisian:
      return Frisian;
    case QLocale::Galician:
      return Galician;
    case QLocale::Georgian:
      return Georgian;
    case QLocale::German:
      return German;
    case QLocale::Greek:
      return Greek;
    case QLocale::Gujarati:
      return Gujarati;
    case QLocale::Haitian:
      return HaitianCreole;
    case QLocale::Hausa:
      return Hausa;
    case QLocale::Hawaiian:
      return Hawaiian;
    case QLocale::Hebrew:
      return Hebrew;
    case QLocale::Hindi:
      return Hindi;
    case QLocale::Hungarian:
      return Hungarian;
    case QLocale::Icelandic:
      return Icelandic;
    case QLocale::Igbo:
      return Igbo;
    case QLocale::Indonesian:
      return Indonesian;
    case QLocale::Irish:
      return Irish;
    case QLocale::Italian:
      return Italian;
    case QLocale::Japanese:
      return Japanese;
    case QLocale::Javanese:
      return Javanese;
    case QLocale::Kannada:
      return Kannada;
    case QLocale::Kazakh:
      return Kazakh;
    case QLocale::Khmer:
      return Khmer;
    case QLocale::Kinyarwanda:
      return Kinyarwanda;
    case QLocale::Korean:
      return Korean;
    case QLocale::Kurdish:
      return Kurdish;
    case QLocale::Lao:
      return Lao;
    case QLocale::Latin:
      return Latin;
    case QLocale::Latvian:
      return Latvian;
    case QLocale::Lithuanian:
      return Lithuanian;
    case QLocale::Luxembourgish:
      return Luxembourgish;
    case QLocale::Macedonian:
      return Macedonian;
    case QLocale::Malagasy:
      return Malagasy;
    case QLocale::Malay:
      return Malay;
    case QLocale::Malayalam:
      return Malayalam;
    case QLocale::Maltese:
      return Maltese;
    case QLocale::Maori:
      return Maori;
    case QLocale::Marathi:
      return Marathi;
    case QLocale::Mongolian:
      return Mongolian;
    case QLocale::Nepali:
      return Nepali;
    case QLocale::NorwegianBokmal:
      return Norwegian;
    case QLocale::Oriya:
      return Oriya;
    case QLocale::Pashto:
      return Pashto;
    case QLocale::Persian:
      return Persian;
    case QLocale::Polish:
      return Polish;
    case QLocale::Portuguese:
      return Portuguese;
    case QLocale::Punjabi:
      return Punjabi;
    case QLocale::Romanian:
      return Romanian;
    case QLocale::Russian:
      return Russian;
    case QLocale::Samoan:
      return Samoan;
    case QLocale::Gaelic:
      return ScotsGaelic;
    case QLocale::Serbian:
      return SerbianCyrillic;
    case QLocale::Shona:
      return Shona;
    case QLocale::Sindhi:
      return Sindhi;
    case QLocale::Sinhala:
      return Sinhala;
    case QLocale::Slovak:
      return Slovak;
    case QLocale::Slovenian:
      return Slovenian;
    case QLocale::Somali:
      return Somali;
    case QLocale::Spanish:
      return Spanish;
    case QLocale::Sundanese:
      return Sundanese;
    case QLocale::Swahili:
      return Swahili;
    case QLocale::Swedish:
      return Swedish;
    case QLocale::Filipino:
      return Filipino;
    case QLocale::Tajik:
      return Tajik;
    case QLocale::Tamil:
      return Tamil;
    case QLocale::Tatar:
      return Tatar;
    case QLocale::Telugu:
      return Telugu;
    case QLocale::Thai:
      return Thai;
    case QLocale::Turkish:
      return Turkish;
    case QLocale::Turkmen:
      return Turkmen;
    case QLocale::Uighur:
      return Uighur;
    case QLocale::Ukrainian:
      return Ukrainian;
    case QLocale::Urdu:
      return Urdu;
    case QLocale::Uzbek:
      return Uzbek;
    case QLocale::Vietnamese:
      return Vietnamese;
    case QLocale::Welsh:
      return Welsh;
    case QLocale::Xhosa:
      return Xhosa;
    case QLocale::Yiddish:
      return Yiddish;
    case QLocale::Yoruba:
      return Yoruba;
    case QLocale::Zulu:
      return Zulu;
    default:
      return English;
  }
}

QString Translator::getLanguageCode(Translator::Language lang) {
  return genericLang2Code[lang];
}
